### ISSUE TITLE
demo_site运行都报错？！

### ISSUE THREAD

**Issue by shineforever** [aliyun/django-oss-storage#1]
环境说明：
Python 2.7.10
Django (1.9)
配置好配置文件后：
1）执行 python manage.py collectstatic 
发现静态文件已经同步到阿里云oss成功，说明配置没有问题；
2）执行 python manage.py migrate 没有报错
3）启动服务：python manage.py runserver 0.0.0.0:8888
访问页面 http://127.0.0.1:8888
报错如下：

$ python manage.py runserver 0.0.0.0:8888
Performing system checks...

System check identified no issues (0 silenced).
September 06, 2017 - 09:32:18
Django version 1.9, using settings 'demo_site.settings'
Starting development server at http://0.0.0.0:8888/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/shine_forever/.virtualenvs/wh716/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/shine_forever/.virtualenvs/wh716/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shine_forever/local_coding/django-oss-storage/demo_site/demo_site/views.py", line 8, in home
    'Default user & password are both "admin".')
  File "/Users/shine_forever/.virtualenvs/wh716/lib/python2.7/site-packages/django/contrib/messages/api.py", line 27, in add_message
    raise MessageFailure('You cannot add messages without installing '
MessageFailure: You cannot add messages without installing django.contrib.messages.middleware.MessageMiddleware

**Comment by abo321** [comment]
谢谢您的反馈。请使用django>=1.10版本。

install_requires=['django>=1.10',
                      'oss2>=2.3.3'],
