### ISSUE TITLE
python manage.py collectstatic run error！

### ISSUE THREAD

**Issue by gexingavin** [aliyun/django-oss-storage#2]
按照步骤配置以后，运行python manage.py collectstatic，得到以下错误：
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/gavin/.virtualenvs/djangodev/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/gavin/.virtualenvs/djangodev/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/gavin/.virtualenvs/djangodev/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/gavin/.virtualenvs/djangodev/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/gavin/.virtualenvs/djangodev/lib/python3.5/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/home/gavin/.virtualenvs/djangodev/lib/python3.5/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/gavin/.virtualenvs/djangodev/lib/python3.5/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/gavin/django/codingtang/judge/admin.py", line 4, in <module>
    from .forms import ClsForm, ExamUsersForm, ProblemForm
  File "/home/gavin/django/codingtang/judge/forms.py", line 4, in <module>
    from pagedown.widgets import AdminPagedownWidget
  File "/home/gavin/.virtualenvs/djangodev/lib/python3.5/site-packages/pagedown/widgets.py", line 69, in <module>
    class AdminPagedownWidget(PagedownWidget, admin_widgets.AdminTextareaWidget):
  File "/home/gavin/.virtualenvs/djangodev/lib/python3.5/site-packages/pagedown/widgets.py", line 70, in AdminPagedownWidget
    class Media:
  File "/home/gavin/.virtualenvs/djangodev/lib/python3.5/site-packages/pagedown/widgets.py", line 72, in Media
    "all": (compatible_staticpath("admin/css/pagedown.css"),)
  File "/home/gavin/.virtualenvs/djangodev/lib/python3.5/site-packages/pagedown/utils.py", line 13, in compatible_staticpath
    return static(path)
  File "/home/gavin/.virtualenvs/djangodev/lib/python3.5/site-packages/django/templatetags/static.py", line 163, in static
    return StaticNode.handle_simple(path)
  File "/home/gavin/.virtualenvs/djangodev/lib/python3.5/site-packages/django/templatetags/static.py", line 114, in handle_simple
    return staticfiles_storage.url(path)
TypeError: url() missing 1 required positional argument: 'expire'

**Comment by abo321** [comment]
谢谢您的反馈。请问下您使用的django是什么版本？

**Comment by gexingavin** [comment]
1.10

**Comment by gzhang** [comment]
1.11.2 Python 3.6 遇到同样问题。
手动给backends.py 的url() 设置expire 默认值解决

**Comment by hbwxl** [comment]
@gzhang 请问这个值设为多少比较合适？有什么用途吗

**Comment by gzhang** [comment]
设置URL过期时间。
expires – 过期时间（单位：秒），链接在当前时间再过expires秒后过期
详见http://aliyun-oss-python-sdk.readthedocs.io/en/stable/_modules/oss2/api.html#Bucket.sign_url
